# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "976c720a22c8eb4eb6a0b4348ad85ad12491a506";
      sha256 = "0a2gxvqzacrj9k8h022zhr8fchhn9afc6a511m07j71dzw9g4y3m";
    };
  }
  {
    goPackagePath = "bazil.org/fuse";
    fetch = {
      type = "git";
      url = "https://github.com/bazil/fuse";
      rev = "371fbbdaa8987b715bdd21d6adc4c9b20155f748";
      sha256 = "1x5p301py7mcxgwklfm6pqqkzssln0nfzllng49pnk60m03ilp4w";
    };
  }
  {
    goPackagePath = "cloud.google.com/go";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/gocloud";
      rev = "90296fd601ebfc594192e722a022663b0c3f8756";
      sha256 = "0qg0d1afhqmpfaq2lh29c87d18s5148yshg0s295dhzdn1m9nhww";
    };
  }
  {
    goPackagePath = "github.com/Unknwon/goconfig";
    fetch = {
      type = "git";
      url = "https://github.com/Unknwon/goconfig";
      rev = "5aa4f8cd5a472c2411c778b4680f59f2223f1966";
      sha256 = "0r6na17sz762c1dyn6gb16v2zhvzg6krmz7pcjg1m0l5wxdf4n0d";
    };
  }
  {
    goPackagePath = "github.com/VividCortex/ewma";
    fetch = {
      type = "git";
      url = "https://github.com/VividCortex/ewma";
      rev = "c595cd886c223c6c28fc9ae2727a61b5e4693d85";
      sha256 = "0f09886vm4rkhgqqh2b20r8rws4syvny3la107hh6qby027bpab2";
    };
  }
  {
    goPackagePath = "github.com/aws/aws-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/aws/aws-sdk-go";
      rev = "388802d0cf038f72020ee99b51781d181e894c1c";
      sha256 = "1clkcd9pcqzbn9vjiflk8yzxly7m88mas4bwzi7ci0446zdw5xqp";
    };
  }
  {
    goPackagePath = "github.com/cpuguy83/go-md2man";
    fetch = {
      type = "git";
      url = "https://github.com/cpuguy83/go-md2man";
      rev = "a65d4d2de4d5f7c74868dfa9b202a3c8be315aaa";
      sha256 = "1rm3zjrmfpzy0l3qp02xmd5pqzl77pdql9pbxhl0k1qw2vfzrjv6";
    };
  }
  {
    goPackagePath = "github.com/go-ini/ini";
    fetch = {
      type = "git";
      url = "https://github.com/go-ini/ini";
      rev = "6e4869b434bd001f6983749881c7ead3545887d8";
      sha256 = "1w7qcl0k7bsp6871vr8mbli09imd67qqq1vbvpll33d2vw12wmva";
    };
  }
  {
    goPackagePath = "github.com/google/go-querystring";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-querystring";
      rev = "9235644dd9e52eeae6fa48efd539fdc351a0af53";
      sha256 = "0q398679fwp7vlnpd2rlzz452a7a4qvpcspak81psfl3xwimpzgq";
    };
  }
  {
    goPackagePath = "github.com/jmespath/go-jmespath";
    fetch = {
      type = "git";
      url = "https://github.com/jmespath/go-jmespath";
      rev = "bd40a432e4c76585ef6b72d3fd96fb9b6dc7b68d";
      sha256 = "1kgzwiyqn24ba9kgpjxlq1h746gnyby0psbjj9mp2yx0h1i0kc4z";
    };
  }
  {
    goPackagePath = "github.com/ncw/go-acd";
    fetch = {
      type = "git";
      url = "https://github.com/ncw/go-acd";
      rev = "56da839497f9854a91f99fe752c33c7977a6f48b";
      sha256 = "1va6hpl73ps443r0s2icplcx113gkhmi2gbsgpaw2iii5lji5085";
    };
  }
  {
    goPackagePath = "github.com/ncw/rclone";
    fetch = {
      type = "git";
      url = "https://github.com/ncw/rclone";
      rev = "f2eeb4301cc04a68633eba7f51fa69a4fd9bb32c";
      sha256 = "1saq98i5c5dqljp4qibbws5z305m6n5p4p61bjajw3r1kgxz1wmb";
    };
  }
  {
    goPackagePath = "github.com/ncw/swift";
    fetch = {
      type = "git";
      url = "https://github.com/ncw/swift";
      rev = "b964f2ca856aac39885e258ad25aec08d5f64ee6";
      sha256 = "0c86ap1zb56r6g96cnbn5j3i3r96c5l8rl98h3sxlqi5agwp3km4";
    };
  }
  {
    goPackagePath = "github.com/ogier/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/ogier/pflag";
      rev = "45c278ab3607870051a2ea9040bb85fcb8557481";
      sha256 = "0620v75wppfd84d95n312wpngcb73cph4q3ivs1h0waljfnsrd5l";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "645ef00459ed84a119197bfb8d8205042c6df63d";
      sha256 = "001i6n71ghp2l6kdl3qq1v2vmghcz3kicv9a5wgcihrzigm75pp5";
    };
  }
  {
    goPackagePath = "github.com/rfjakob/eme";
    fetch = {
      type = "git";
      url = "https://github.com/rfjakob/eme";
      rev = "601d0e278ceda9aa2085a61c9265f6e690ef5255";
      sha256 = "1ryh5f2a42psrqcpjh73shk3p0mva2vcyyfav4nhxmfqall77k5z";
    };
  }
  {
    goPackagePath = "github.com/russross/blackfriday";
    fetch = {
      type = "git";
      url = "https://github.com/russross/blackfriday";
      rev = "35eb537633d9950afc8ae7bdf0edb6134584e9fc";
      sha256 = "1hwi1nq5kkpcci7lf4fwhs8jj0mf6xcbdz1vgijpfyyd0zr6mphc";
    };
  }
  {
    goPackagePath = "github.com/shurcooL/sanitized_anchor_name";
    fetch = {
      type = "git";
      url = "https://github.com/shurcooL/sanitized_anchor_name";
      rev = "1dba4b3954bc059efc3991ec364f9f9a35f597d2";
      sha256 = "0pwap8lp79pldd95a1qi3xhlsa17m8zddpgc5jzvk6d1cjpsm6qg";
    };
  }
  {
    goPackagePath = "github.com/skratchdot/open-golang";
    fetch = {
      type = "git";
      url = "https://github.com/skratchdot/open-golang";
      rev = "75fb7ed4208cf72d323d7d02fd1a5964a7a9073c";
      sha256 = "1b67imqbsdvg19vif1q1dfmapxy3v2anagacbql95fwnnw0v8jga";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "9c28e4bbd74e5c3ed7aacbc552b2cab7cfdfe744";
      sha256 = "02bgp0yy9bi05k2in9axqi3db1c6mjffdsmki51pn9iryxz4zkh3";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "c7e63cf4530bcd3ba943729cee0efeff2ebea63f";
      sha256 = "197mlkgb01zk86fxfl8r8maymcxsspqblg7hmngjxf7ivdid1i1l";
    };
  }
  {
    goPackagePath = "github.com/stacktic/dropbox";
    fetch = {
      type = "git";
      url = "https://github.com/stacktic/dropbox";
      rev = "58f839b21094d5e0af7caf613599830589233d20";
      sha256 = "1psmxpnn40ri9bgjvivljnd4p977f635mh3w7m5mglxxgc9392pi";
    };
  }
  {
    goPackagePath = "github.com/tsenart/tb";
    fetch = {
      type = "git";
      url = "https://github.com/tsenart/tb";
      rev = "19f4c3d79d2bd67d0911b2e310b999eeea4454c1";
      sha256 = "148vy4xij5qm8dq5plyczx2wbpi4gpg8ksr5r3b4m8j0z1kjws8y";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "568507f56e5b05b3c219ffd7fba12655c07bcc86";
      sha256 = "1w1bqr3plimkv8lapjh5s9vwb5dwnylysmspjb2chdy4fqmkpv9r";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "0d8126fc6144eb5257485c59148128691e8ff849";
      sha256 = "1w796dd27wpw7b1hvx94njr8iw4ka83lpkms0g98xhbky3w9n126";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "3c3a985cb79f52a3190fbc056984415ca6763d01";
      sha256 = "0c7x8wkya56z03j2qfm61932npsddgqyggi75hkla9755d1inqlv";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "8f0908ab3b2457e2e15403d3697c9ef5cb4b57a9";
      sha256 = "04va4pqygfzr89fx873k44bmivk7nybqalybi6q96lnn45h2scbr";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "a7c023693a94aedd6b6df43ae7526bfe9d2b7d22";
      sha256 = "19kq5w431zrv1v4sd4ddzrafgz2dwcyrjzcdxp6yrzj2c3akpb71";
    };
  }
  {
    goPackagePath = "google.golang.org/api";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/google-api-go-client";
      rev = "adba394bac5800ff2e620d040e9401528f5b7615";
      sha256 = "1k43fpn76cjcpw7kb95hvfkgc3ssnaxf1h6jlfbbfls7ydl01shy";
    };
  }
]
